### ISSUE TITLE
Provide an option for showing only those event types which have been added to a release

### ISSUE THREAD

**Issue by gunnarmorling** [parttimenerd/jfrevents-site-generator#2]
Congrats on this nice project! In addition to seeing _all_ the JFR event types available from a given Java version, it would also be very useful to be able to see which events have been _added_ in a particular version.

One option for doing this might be to render a "filtered" page per Java version--only showing any new types--in addition to the page with all the event types of that version. Alternatively, a matrix view like [the one in the JFR-Events](https://bestsolution-at.github.io/jfr-doc/openjdk-matrix.html) project could be provided (which unfortunately hasn't been updated after Java 18).

**Comment by parttimenerd** [comment]
This is a great idea and, at first glance, is easily implementable.
